// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNORLuK4OeGvoEYYElhNlgEw5SrjYUSZM',
    appId: '1:739339976487:web:c9d1d13ecfe26f1cf5f302',
    messagingSenderId: '739339976487',
    projectId: 'super-market-artawia',
    authDomain: 'super-market-artawia.firebaseapp.com',
    storageBucket: 'super-market-artawia.firebasestorage.app',
    measurementId: 'G-7NKDC5MY82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPeXWVNMrCMMR057n5NZRDOg_kW7BRpp0',
    appId: '1:739339976487:android:9edd831d33fdef10f5f302',
    messagingSenderId: '739339976487',
    projectId: 'super-market-artawia',
    storageBucket: 'super-market-artawia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvF1lJS2tApiKChdML2l3IRCwy0iX5jWo',
    appId: '1:739339976487:ios:1a6672ca7160c4a8f5f302',
    messagingSenderId: '739339976487',
    projectId: 'super-market-artawia',
    storageBucket: 'super-market-artawia.firebasestorage.app',
    iosBundleId: 'com.example.fadaAlhalijWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvF1lJS2tApiKChdML2l3IRCwy0iX5jWo',
    appId: '1:739339976487:ios:1a6672ca7160c4a8f5f302',
    messagingSenderId: '739339976487',
    projectId: 'super-market-artawia',
    storageBucket: 'super-market-artawia.firebasestorage.app',
    iosBundleId: 'com.example.fadaAlhalijWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNORLuK4OeGvoEYYElhNlgEw5SrjYUSZM',
    appId: '1:739339976487:web:996261cfd7ee4d51f5f302',
    messagingSenderId: '739339976487',
    projectId: 'super-market-artawia',
    authDomain: 'super-market-artawia.firebaseapp.com',
    storageBucket: 'super-market-artawia.firebasestorage.app',
    measurementId: 'G-TNQVR55NM4',
  );

}