// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbYpYQbkXuYZR-7yHq5WmwbG5OblPOtCU',
    appId: '1:191929514173:web:51219f9be2aef7035ddfd4',
    messagingSenderId: '191929514173',
    projectId: 'supermarket-amjad',
    authDomain: 'supermarket-amjad.firebaseapp.com',
    storageBucket: 'supermarket-amjad.firebasestorage.app',
    measurementId: 'G-E73SX6TBHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7CeU16aou5DvGV2Lm9U7ZRZuta-LGa2Q',
    appId: '1:191929514173:android:95906d6b334436715ddfd4',
    messagingSenderId: '191929514173',
    projectId: 'supermarket-amjad',
    storageBucket: 'supermarket-amjad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUkbhTbT70mZvtccQfZbZZB6TbdEJNqW8',
    appId: '1:191929514173:ios:1294f69690ada3015ddfd4',
    messagingSenderId: '191929514173',
    projectId: 'supermarket-amjad',
    storageBucket: 'supermarket-amjad.firebasestorage.app',
    iosBundleId: 'com.example.fadaAlhalijWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUkbhTbT70mZvtccQfZbZZB6TbdEJNqW8',
    appId: '1:191929514173:ios:1294f69690ada3015ddfd4',
    messagingSenderId: '191929514173',
    projectId: 'supermarket-amjad',
    storageBucket: 'supermarket-amjad.firebasestorage.app',
    iosBundleId: 'com.example.fadaAlhalijWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbYpYQbkXuYZR-7yHq5WmwbG5OblPOtCU',
    appId: '1:191929514173:web:858cee3d567433025ddfd4',
    messagingSenderId: '191929514173',
    projectId: 'supermarket-amjad',
    authDomain: 'supermarket-amjad.firebaseapp.com',
    storageBucket: 'supermarket-amjad.firebasestorage.app',
    measurementId: 'G-XC30244J1W',
  );

}